// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZAD.Persistence.Context;

#nullable disable

namespace ZAD.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260827183627_AddReceiveVehicleFields")]
    partial class AddReceiveVehicleFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZAD.Domain.Entities.Branches.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CostCenter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMainBranch")
                        .HasColumnType("bit");

                    b.Property<string>("LogoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CompanyId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("ZAD.Domain.Entities.Companies.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("ZAD.Domain.Entities.Lookups.Lookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LookupKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("LookupKey", "Culture")
                        .IsUnique();

                    b.ToTable("Lookups");
                });

            modelBuilder.Entity("ZAD.Domain.Entities.VehicleRental.Contracts.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AccidentPenalty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("AccountingNo")
                        .HasColumnType("int");

                    b.Property<int>("ActualPeriodInDays")
                        .HasColumnType("int");

                    b.Property<int>("AllowedDelayHours")
                        .HasColumnType("int");

                    b.Property<decimal>("AmountOfKmExceedingLimit")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("ContractType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DelayHours")
                        .HasColumnType("int");

                    b.Property<decimal?>("DelayPenaltyAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DelayPenaltyPerHour")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("DeliveryStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("DriverFare")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<decimal>("DriverOvertimeAmountPerHour")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("DriverWorkingHoursPerDay")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpectedReceivingDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("ExpectedReceivingTime")
                        .HasColumnType("time");

                    b.Property<decimal?>("FinalNetDueAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("FreeKM")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("KMExceededTheLimit")
                        .HasColumnType("int");

                    b.Property<int>("KilometerCounter")
                        .HasColumnType("int");

                    b.Property<int>("KilometerPerDay")
                        .HasColumnType("int");

                    b.Property<decimal>("MaintenancePaidByTenant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MaintenancePenalty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("MaximumKilometerPerDay")
                        .HasColumnType("int");

                    b.Property<decimal>("NetRentPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<int>("PeriodInDays")
                        .HasColumnType("int");

                    b.Property<decimal>("ReceiveDiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReceiveNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ReceiveProofDocuments")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReceivingDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReceivingKilometerCounter")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("ReceivingTime")
                        .HasColumnType("time");

                    b.Property<decimal>("RemainingAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("RentPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("RentalVehicleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SecondDriverIdExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecondDriverIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SecondDriverLicenseExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecondDriverLicenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondDriverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondDriverNationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SponsorIdExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SponsorIdNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("SponsorLicenseExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SponsorLicenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SponsorName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SponsorNationality")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.Property<decimal?>("TotalAmountOfKMExceedingTheLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TotalConsumptionKilometers")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalDriverAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalDueAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalRentalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("WithDriver")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DriverId");

                    b.HasIndex("RentalVehicleId");

                    b.HasIndex("TenantId");

                    b.ToTable("Contracts", (string)null);
                });

            modelBuilder.Entity("ZAD.Domain.Entities.VehicleRental.Drivers.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Drivers", (string)null);
                });

            modelBuilder.Entity("ZAD.Domain.Entities.VehicleRental.Drivers.SecondDriver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IdExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LicenseExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SecondDrivers");
                });

            modelBuilder.Entity("ZAD.Domain.Entities.VehicleRental.Sponsors.Sponsor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IdExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LicenseExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Sponsors");
                });

            modelBuilder.Entity("ZAD.Domain.Entities.VehicleRental.Tenants.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UnifiedNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tenants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthday = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1001",
                            IsDeleted = false,
                            LicenseNumber = "L1001",
                            Mobile = "01000000001",
                            Name = "أحمد محمود",
                            PassportNumber = "P1001",
                            UnifiedNumber = "U1001"
                        },
                        new
                        {
                            Id = 2,
                            Birthday = new DateTime(1985, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1002",
                            IsDeleted = false,
                            LicenseNumber = "L1002",
                            Mobile = "01000000002",
                            Name = "محمد علي",
                            PassportNumber = "P1002",
                            UnifiedNumber = "U1002"
                        },
                        new
                        {
                            Id = 3,
                            Birthday = new DateTime(1992, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1003",
                            IsDeleted = false,
                            LicenseNumber = "L1003",
                            Mobile = "01000000003",
                            Name = "محمود حسن",
                            PassportNumber = "P1003",
                            UnifiedNumber = "U1003"
                        },
                        new
                        {
                            Id = 4,
                            Birthday = new DateTime(1988, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1004",
                            IsDeleted = false,
                            LicenseNumber = "L1004",
                            Mobile = "01000000004",
                            Name = "عمر فاروق",
                            PassportNumber = "P1004",
                            UnifiedNumber = "U1004"
                        },
                        new
                        {
                            Id = 5,
                            Birthday = new DateTime(1995, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1005",
                            IsDeleted = false,
                            LicenseNumber = "L1005",
                            Mobile = "01000000005",
                            Name = "عبد الله إبراهيم",
                            PassportNumber = "P1005",
                            UnifiedNumber = "U1005"
                        },
                        new
                        {
                            Id = 6,
                            Birthday = new DateTime(1980, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1006",
                            IsDeleted = false,
                            LicenseNumber = "L1006",
                            Mobile = "01000000006",
                            Name = "يوسف مصطفى",
                            PassportNumber = "P1006",
                            UnifiedNumber = "U1006"
                        },
                        new
                        {
                            Id = 7,
                            Birthday = new DateTime(1975, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1007",
                            IsDeleted = false,
                            LicenseNumber = "L1007",
                            Mobile = "01000000007",
                            Name = "حسين عبد الرحمن",
                            PassportNumber = "P1007",
                            UnifiedNumber = "U1007"
                        },
                        new
                        {
                            Id = 8,
                            Birthday = new DateTime(1999, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1008",
                            IsDeleted = false,
                            LicenseNumber = "L1008",
                            Mobile = "01000000008",
                            Name = "سعيد سليمان",
                            PassportNumber = "P1008",
                            UnifiedNumber = "U1008"
                        },
                        new
                        {
                            Id = 9,
                            Birthday = new DateTime(1971, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1009",
                            IsDeleted = false,
                            LicenseNumber = "L1009",
                            Mobile = "01000000009",
                            Name = "طارق يحيى",
                            PassportNumber = "P1009",
                            UnifiedNumber = "U1009"
                        },
                        new
                        {
                            Id = 10,
                            Birthday = new DateTime(1982, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1010",
                            IsDeleted = false,
                            LicenseNumber = "L1010",
                            Mobile = "01000000010",
                            Name = "حسن حمدي",
                            PassportNumber = "P1010",
                            UnifiedNumber = "U1010"
                        },
                        new
                        {
                            Id = 11,
                            Birthday = new DateTime(1993, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1011",
                            IsDeleted = false,
                            LicenseNumber = "L1011",
                            Mobile = "01000000011",
                            Name = "خالد زكي",
                            PassportNumber = "P1011",
                            UnifiedNumber = "U1011"
                        },
                        new
                        {
                            Id = 12,
                            Birthday = new DateTime(1978, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1012",
                            IsDeleted = false,
                            LicenseNumber = "L1012",
                            Mobile = "01000000012",
                            Name = "ماجد الكدواني",
                            PassportNumber = "P1012",
                            UnifiedNumber = "U1012"
                        },
                        new
                        {
                            Id = 13,
                            Birthday = new DateTime(1989, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1013",
                            IsDeleted = false,
                            LicenseNumber = "L1013",
                            Mobile = "01000000013",
                            Name = "أمير كرارة",
                            PassportNumber = "P1013",
                            UnifiedNumber = "U1013"
                        },
                        new
                        {
                            Id = 14,
                            Birthday = new DateTime(1996, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1014",
                            IsDeleted = false,
                            LicenseNumber = "L1014",
                            Mobile = "01000000014",
                            Name = "صالح جمعة",
                            PassportNumber = "P1014",
                            UnifiedNumber = "U1014"
                        },
                        new
                        {
                            Id = 15,
                            Birthday = new DateTime(1997, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1015",
                            IsDeleted = false,
                            LicenseNumber = "L1015",
                            Mobile = "01000000015",
                            Name = "عبد الله جمعة",
                            PassportNumber = "P1015",
                            UnifiedNumber = "U1015"
                        },
                        new
                        {
                            Id = 16,
                            Birthday = new DateTime(1991, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1016",
                            IsDeleted = false,
                            LicenseNumber = "L1016",
                            Mobile = "01000000016",
                            Name = "باسم مرسي",
                            PassportNumber = "P1016",
                            UnifiedNumber = "U1016"
                        },
                        new
                        {
                            Id = 17,
                            Birthday = new DateTime(1979, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1017",
                            IsDeleted = false,
                            LicenseNumber = "L1017",
                            Mobile = "01000000017",
                            Name = "حازم إمام",
                            PassportNumber = "P1017",
                            UnifiedNumber = "U1017"
                        },
                        new
                        {
                            Id = 18,
                            Birthday = new DateTime(1973, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1018",
                            IsDeleted = false,
                            LicenseNumber = "L1018",
                            Mobile = "01000000018",
                            Name = "عصام الحضري",
                            PassportNumber = "P1018",
                            UnifiedNumber = "U1018"
                        },
                        new
                        {
                            Id = 19,
                            Birthday = new DateTime(1976, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1019",
                            IsDeleted = false,
                            LicenseNumber = "L1019",
                            Mobile = "01000000019",
                            Name = "وائل جمعة",
                            PassportNumber = "P1019",
                            UnifiedNumber = "U1019"
                        },
                        new
                        {
                            Id = 20,
                            Birthday = new DateTime(1978, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1020",
                            IsDeleted = false,
                            LicenseNumber = "L1020",
                            Mobile = "01000000020",
                            Name = "محمد أبو تريكة",
                            PassportNumber = "P1020",
                            UnifiedNumber = "U1020"
                        },
                        new
                        {
                            Id = 21,
                            Birthday = new DateTime(1975, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1021",
                            IsDeleted = false,
                            LicenseNumber = "L1021",
                            Mobile = "01000000021",
                            Name = "أحمد حسن",
                            PassportNumber = "P1021",
                            UnifiedNumber = "U1021"
                        },
                        new
                        {
                            Id = 22,
                            Birthday = new DateTime(1992, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1022",
                            IsDeleted = false,
                            LicenseNumber = "L1022",
                            Mobile = "01000000022",
                            Name = "محمد صلاح",
                            PassportNumber = "P1022",
                            UnifiedNumber = "U1022"
                        },
                        new
                        {
                            Id = 23,
                            Birthday = new DateTime(1994, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1023",
                            IsDeleted = false,
                            LicenseNumber = "L1023",
                            Mobile = "01000000023",
                            Name = "محمود تريزيجيه",
                            PassportNumber = "P1023",
                            UnifiedNumber = "U1023"
                        },
                        new
                        {
                            Id = 24,
                            Birthday = new DateTime(1999, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1024",
                            IsDeleted = false,
                            LicenseNumber = "L1024",
                            Mobile = "01000000024",
                            Name = "عمر مرموش",
                            PassportNumber = "P1024",
                            UnifiedNumber = "U1024"
                        },
                        new
                        {
                            Id = 25,
                            Birthday = new DateTime(1997, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1025",
                            IsDeleted = false,
                            LicenseNumber = "L1025",
                            Mobile = "01000000025",
                            Name = "مصطفى محمد",
                            PassportNumber = "P1025",
                            UnifiedNumber = "U1025"
                        });
                });

            modelBuilder.Entity("ZAD.Domain.Entities.VehicleRental.Vehicles.RentalVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DailyRentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FileNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("HourlyRentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRented")
                        .HasColumnType("bit");

                    b.Property<int>("KilometerCounter")
                        .HasColumnType("int");

                    b.Property<int>("ModelYear")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyRentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PlateNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("WeeklyRentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("YearlyRentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("RentalVehicles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "KIA Cerato",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRentPrice = 600m,
                            FileNo = "F-001",
                            HourlyRentPrice = 60m,
                            IsDeleted = false,
                            IsRented = true,
                            KilometerCounter = 10000,
                            ModelYear = 2026,
                            MonthlyRentPrice = 12000m,
                            PlateNo = "77777",
                            Type = 1,
                            WeeklyRentPrice = 3600m,
                            YearlyRentPrice = 120000m
                        },
                        new
                        {
                            Id = 2,
                            Brand = "KIA Sportage",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRentPrice = 800m,
                            FileNo = "F-002",
                            HourlyRentPrice = 80m,
                            IsDeleted = false,
                            IsRented = true,
                            KilometerCounter = 12000,
                            ModelYear = 2026,
                            MonthlyRentPrice = 16000m,
                            PlateNo = "3030",
                            Type = 1,
                            WeeklyRentPrice = 4800m,
                            YearlyRentPrice = 160000m
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Toyota Hiace",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRentPrice = 1200m,
                            FileNo = "F-003",
                            HourlyRentPrice = 120m,
                            IsDeleted = false,
                            IsRented = true,
                            KilometerCounter = 15000,
                            ModelYear = 2026,
                            MonthlyRentPrice = 24000m,
                            PlateNo = "EXT 1111",
                            Type = 2,
                            WeeklyRentPrice = 7200m,
                            YearlyRentPrice = 240000m
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Nissan Patrol",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRentPrice = 1500m,
                            FileNo = "F-004",
                            HourlyRentPrice = 150m,
                            IsDeleted = false,
                            IsRented = true,
                            KilometerCounter = 20000,
                            ModelYear = 2026,
                            MonthlyRentPrice = 30000m,
                            PlateNo = "ACB-4578",
                            Type = 1,
                            WeeklyRentPrice = 9000m,
                            YearlyRentPrice = 300000m
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Kia Sonet",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRentPrice = 700m,
                            FileNo = "F-005",
                            HourlyRentPrice = 70m,
                            IsDeleted = false,
                            IsRented = true,
                            KilometerCounter = 8000,
                            ModelYear = 2026,
                            MonthlyRentPrice = 14000m,
                            PlateNo = "ABC 1245",
                            Type = 1,
                            WeeklyRentPrice = 4200m,
                            YearlyRentPrice = 140000m
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Kia Sonet",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRentPrice = 400m,
                            FileNo = "DEF 1478",
                            HourlyRentPrice = 40m,
                            IsDeleted = false,
                            IsRented = false,
                            KilometerCounter = 40000,
                            ModelYear = 2011,
                            MonthlyRentPrice = 8000m,
                            PlateNo = "DEF 1478",
                            Type = 1,
                            WeeklyRentPrice = 2400m,
                            YearlyRentPrice = 80000m
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Toyota Corolla",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRentPrice = 700m,
                            FileNo = "F-007",
                            HourlyRentPrice = 70m,
                            IsDeleted = false,
                            IsRented = false,
                            KilometerCounter = 5000,
                            ModelYear = 2026,
                            MonthlyRentPrice = 14000m,
                            PlateNo = "XYZ 999",
                            Type = 1,
                            WeeklyRentPrice = 4200m,
                            YearlyRentPrice = 140000m
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Toyota Coaster",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRentPrice = 1500m,
                            FileNo = "F-008",
                            HourlyRentPrice = 150m,
                            IsDeleted = false,
                            IsRented = false,
                            KilometerCounter = 6000,
                            ModelYear = 2026,
                            MonthlyRentPrice = 30000m,
                            PlateNo = "LMN 456",
                            Type = 2,
                            WeeklyRentPrice = 9000m,
                            YearlyRentPrice = 300000m
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Honda Civic",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRentPrice = 750m,
                            FileNo = "F-009",
                            HourlyRentPrice = 75m,
                            IsDeleted = false,
                            IsRented = false,
                            KilometerCounter = 7000,
                            ModelYear = 2026,
                            MonthlyRentPrice = 15000m,
                            PlateNo = "PQR 789",
                            Type = 1,
                            WeeklyRentPrice = 4500m,
                            YearlyRentPrice = 150000m
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Hyundai Elantra",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRentPrice = 650m,
                            FileNo = "F-010",
                            HourlyRentPrice = 65m,
                            IsDeleted = false,
                            IsRented = false,
                            KilometerCounter = 9000,
                            ModelYear = 2026,
                            MonthlyRentPrice = 13000m,
                            PlateNo = "STU 123",
                            Type = 1,
                            WeeklyRentPrice = 3900m,
                            YearlyRentPrice = 130000m
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Chevrolet NPR",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRentPrice = 2000m,
                            FileNo = "F-011",
                            HourlyRentPrice = 200m,
                            IsDeleted = false,
                            IsRented = false,
                            KilometerCounter = 25000,
                            ModelYear = 2026,
                            MonthlyRentPrice = 40000m,
                            PlateNo = "VWX 456",
                            Type = 3,
                            WeeklyRentPrice = 12000m,
                            YearlyRentPrice = 400000m
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Ford Explorer",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRentPrice = 1200m,
                            FileNo = "F-012",
                            HourlyRentPrice = 120m,
                            IsDeleted = false,
                            IsRented = false,
                            KilometerCounter = 22000,
                            ModelYear = 2026,
                            MonthlyRentPrice = 24000m,
                            PlateNo = "YZA 789",
                            Type = 1,
                            WeeklyRentPrice = 7200m,
                            YearlyRentPrice = 240000m
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Mazda CX-5",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRentPrice = 900m,
                            FileNo = "F-013",
                            HourlyRentPrice = 90m,
                            IsDeleted = false,
                            IsRented = false,
                            KilometerCounter = 14000,
                            ModelYear = 2026,
                            MonthlyRentPrice = 18000m,
                            PlateNo = "BCD 012",
                            Type = 1,
                            WeeklyRentPrice = 5400m,
                            YearlyRentPrice = 180000m
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Nissan Altima",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRentPrice = 750m,
                            FileNo = "F-014",
                            HourlyRentPrice = 75m,
                            IsDeleted = false,
                            IsRented = false,
                            KilometerCounter = 11000,
                            ModelYear = 2026,
                            MonthlyRentPrice = 15000m,
                            PlateNo = "EFG 345",
                            Type = 1,
                            WeeklyRentPrice = 4500m,
                            YearlyRentPrice = 150000m
                        },
                        new
                        {
                            Id = 15,
                            Brand = "BMW 3 Series",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRentPrice = 2000m,
                            FileNo = "F-015",
                            HourlyRentPrice = 200m,
                            IsDeleted = false,
                            IsRented = false,
                            KilometerCounter = 18000,
                            ModelYear = 2026,
                            MonthlyRentPrice = 40000m,
                            PlateNo = "HIJ 678",
                            Type = 1,
                            WeeklyRentPrice = 12000m,
                            YearlyRentPrice = 400000m
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Mercedes S-Class",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRentPrice = 4000m,
                            FileNo = "F-016",
                            HourlyRentPrice = 400m,
                            IsDeleted = false,
                            IsRented = false,
                            KilometerCounter = 16000,
                            ModelYear = 2026,
                            MonthlyRentPrice = 80000m,
                            PlateNo = "KLM 901",
                            Type = 1,
                            WeeklyRentPrice = 24000m,
                            YearlyRentPrice = 800000m
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Audi A4",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRentPrice = 1800m,
                            FileNo = "F-017",
                            HourlyRentPrice = 180m,
                            IsDeleted = false,
                            IsRented = false,
                            KilometerCounter = 17000,
                            ModelYear = 2026,
                            MonthlyRentPrice = 36000m,
                            PlateNo = "NOP 234",
                            Type = 1,
                            WeeklyRentPrice = 10800m,
                            YearlyRentPrice = 360000m
                        },
                        new
                        {
                            Id = 18,
                            Brand = "Lexus ES",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRentPrice = 1600m,
                            FileNo = "F-018",
                            HourlyRentPrice = 160m,
                            IsDeleted = false,
                            IsRented = false,
                            KilometerCounter = 13000,
                            ModelYear = 2026,
                            MonthlyRentPrice = 32000m,
                            PlateNo = "QRS 567",
                            Type = 1,
                            WeeklyRentPrice = 9600m,
                            YearlyRentPrice = 320000m
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Mercedes Sprinter",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRentPrice = 2500m,
                            FileNo = "F-019",
                            HourlyRentPrice = 250m,
                            IsDeleted = false,
                            IsRented = false,
                            KilometerCounter = 21000,
                            ModelYear = 2026,
                            MonthlyRentPrice = 50000m,
                            PlateNo = "TUV 890",
                            Type = 2,
                            WeeklyRentPrice = 15000m,
                            YearlyRentPrice = 500000m
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Volkswagen Tiguan",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRentPrice = 1000m,
                            FileNo = "F-020",
                            HourlyRentPrice = 100m,
                            IsDeleted = false,
                            IsRented = false,
                            KilometerCounter = 19000,
                            ModelYear = 2026,
                            MonthlyRentPrice = 20000m,
                            PlateNo = "WXY 123",
                            Type = 1,
                            WeeklyRentPrice = 6000m,
                            YearlyRentPrice = 200000m
                        },
                        new
                        {
                            Id = 21,
                            Brand = "Mitsubishi Fuso",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRentPrice = 1800m,
                            FileNo = "F-021",
                            HourlyRentPrice = 180m,
                            IsDeleted = false,
                            IsRented = false,
                            KilometerCounter = 24000,
                            ModelYear = 2026,
                            MonthlyRentPrice = 36000m,
                            PlateNo = "ZAB 456",
                            Type = 3,
                            WeeklyRentPrice = 10800m,
                            YearlyRentPrice = 360000m
                        });
                });

            modelBuilder.Entity("ZAD.Domain.Entities.Branches.Branch", b =>
                {
                    b.HasOne("ZAD.Domain.Entities.Companies.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("ZAD.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<int>("BranchId")
                                .HasColumnType("int");

                            b1.Property<string>("AddressAr")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("AddressAr");

                            b1.Property<string>("AddressEn")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("AddressEn");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("City");

                            b1.Property<string>("Country")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Country");

                            b1.HasKey("BranchId");

                            b1.ToTable("Branches");

                            b1.WithOwner()
                                .HasForeignKey("BranchId");
                        });

                    b.OwnsMany("ZAD.Domain.Entities.Common.Contact", "Contacts", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("BranchId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)");

                            b1.HasKey("Id");

                            b1.HasIndex("BranchId");

                            b1.ToTable("BranchContacts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BranchId");
                        });

                    b.OwnsMany("ZAD.Domain.Entities.Common.Document", "Documents", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("BranchId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("DocumentNumber")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<DateTime?>("ExpiryDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("FilePath")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("datetime2");

                            b1.HasKey("Id");

                            b1.HasIndex("BranchId");

                            b1.ToTable("BranchDocuments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BranchId");
                        });

                    b.Navigation("Address");

                    b.Navigation("Company");

                    b.Navigation("Contacts");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("ZAD.Domain.Entities.Companies.Company", b =>
                {
                    b.OwnsOne("ZAD.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<int>("CompanyId")
                                .HasColumnType("int");

                            b1.Property<string>("AddressAr")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("AddressAr");

                            b1.Property<string>("AddressEn")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("AddressEn");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("City");

                            b1.Property<string>("Country")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Country");

                            b1.HasKey("CompanyId");

                            b1.ToTable("Companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.OwnsMany("ZAD.Domain.Entities.Common.Contact", "Contacts", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("CompanyId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)");

                            b1.HasKey("Id");

                            b1.HasIndex("CompanyId");

                            b1.ToTable("CompanyContacts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.OwnsMany("ZAD.Domain.Entities.Common.Document", "Documents", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("CompanyId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("DocumentNumber")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<DateTime?>("ExpiryDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("FilePath")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("datetime2");

                            b1.HasKey("Id");

                            b1.HasIndex("CompanyId");

                            b1.ToTable("CompanyDocuments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.Navigation("Address");

                    b.Navigation("Contacts");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("ZAD.Domain.Entities.VehicleRental.Contracts.Contract", b =>
                {
                    b.HasOne("ZAD.Domain.Entities.Branches.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ZAD.Domain.Entities.Companies.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ZAD.Domain.Entities.VehicleRental.Drivers.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ZAD.Domain.Entities.VehicleRental.Vehicles.RentalVehicle", "RentalVehicle")
                        .WithMany()
                        .HasForeignKey("RentalVehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZAD.Domain.Entities.VehicleRental.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Company");

                    b.Navigation("Driver");

                    b.Navigation("RentalVehicle");

                    b.Navigation("Tenant");
                });
#pragma warning restore 612, 618
        }
    }
}
