// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZAD.Persistence.Context;

#nullable disable

namespace ZAD.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260821122710_SeedVehiclesAndDrivers2026")]
    partial class SeedVehiclesAndDrivers2026
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZAD.Domain.Entities.Branches.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CostCenter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMainBranch")
                        .HasColumnType("bit");

                    b.Property<string>("LogoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CompanyId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("ZAD.Domain.Entities.Companies.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("ZAD.Domain.Entities.Lookups.Lookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LookupKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("LookupKey", "Culture")
                        .IsUnique();

                    b.ToTable("Lookups");
                });

            modelBuilder.Entity("ZAD.Domain.Entities.VehicleRental.Contracts.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AccidentPenalty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("AccountingNo")
                        .HasColumnType("int");

                    b.Property<int>("ActualPeriodInDays")
                        .HasColumnType("int");

                    b.Property<int>("AllowedDelayHours")
                        .HasColumnType("int");

                    b.Property<decimal>("AmountOfKmExceedingLimit")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("ContractType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DelayPenaltyPerHour")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("DeliveryStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("DriverFare")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<decimal>("DriverOvertimeAmountPerHour")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("DriverWorkingHoursPerDay")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpectedReceivingDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("ExpectedReceivingTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPosted")
                        .HasColumnType("bit");

                    b.Property<int>("KilometerCounter")
                        .HasColumnType("int");

                    b.Property<int>("KilometerPerDay")
                        .HasColumnType("int");

                    b.Property<decimal>("MaintenancePenalty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("MaximumKilometerPerDay")
                        .HasColumnType("int");

                    b.Property<decimal>("NetRentPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("NextMaintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NextMaintenanceKm")
                        .HasColumnType("int");

                    b.Property<int?>("NotificationType")
                        .HasColumnType("int");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<int>("PeriodInDays")
                        .HasColumnType("int");

                    b.Property<decimal>("RemainingAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("ReminderBeforePeriodicMaintenance")
                        .HasColumnType("bit");

                    b.Property<decimal>("RentPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("RentalVehicleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SponsorIdExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SponsorIdNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("SponsorLicenseExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SponsorLicenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SponsorName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SponsorNationality")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("WithDriver")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DriverId");

                    b.HasIndex("RentalVehicleId");

                    b.HasIndex("TenantId");

                    b.ToTable("Contracts", (string)null);
                });

            modelBuilder.Entity("ZAD.Domain.Entities.VehicleRental.Drivers.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Drivers", (string)null);
                });

            modelBuilder.Entity("ZAD.Domain.Entities.VehicleRental.Tenants.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UnifiedNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tenants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthday = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1001",
                            IsDeleted = false,
                            LicenseNumber = "L1001",
                            Mobile = "01000000001",
                            Name = "أحمد محمود",
                            PassportNumber = "P1001",
                            UnifiedNumber = "U1001"
                        },
                        new
                        {
                            Id = 2,
                            Birthday = new DateTime(1985, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1002",
                            IsDeleted = false,
                            LicenseNumber = "L1002",
                            Mobile = "01000000002",
                            Name = "محمد علي",
                            PassportNumber = "P1002",
                            UnifiedNumber = "U1002"
                        },
                        new
                        {
                            Id = 3,
                            Birthday = new DateTime(1992, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1003",
                            IsDeleted = false,
                            LicenseNumber = "L1003",
                            Mobile = "01000000003",
                            Name = "محمود حسن",
                            PassportNumber = "P1003",
                            UnifiedNumber = "U1003"
                        },
                        new
                        {
                            Id = 4,
                            Birthday = new DateTime(1988, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1004",
                            IsDeleted = false,
                            LicenseNumber = "L1004",
                            Mobile = "01000000004",
                            Name = "عمر فاروق",
                            PassportNumber = "P1004",
                            UnifiedNumber = "U1004"
                        },
                        new
                        {
                            Id = 5,
                            Birthday = new DateTime(1995, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1005",
                            IsDeleted = false,
                            LicenseNumber = "L1005",
                            Mobile = "01000000005",
                            Name = "عبد الله إبراهيم",
                            PassportNumber = "P1005",
                            UnifiedNumber = "U1005"
                        },
                        new
                        {
                            Id = 6,
                            Birthday = new DateTime(1980, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1006",
                            IsDeleted = false,
                            LicenseNumber = "L1006",
                            Mobile = "01000000006",
                            Name = "يوسف مصطفى",
                            PassportNumber = "P1006",
                            UnifiedNumber = "U1006"
                        },
                        new
                        {
                            Id = 7,
                            Birthday = new DateTime(1975, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1007",
                            IsDeleted = false,
                            LicenseNumber = "L1007",
                            Mobile = "01000000007",
                            Name = "حسين عبد الرحمن",
                            PassportNumber = "P1007",
                            UnifiedNumber = "U1007"
                        },
                        new
                        {
                            Id = 8,
                            Birthday = new DateTime(1999, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1008",
                            IsDeleted = false,
                            LicenseNumber = "L1008",
                            Mobile = "01000000008",
                            Name = "سعيد سليمان",
                            PassportNumber = "P1008",
                            UnifiedNumber = "U1008"
                        },
                        new
                        {
                            Id = 9,
                            Birthday = new DateTime(1971, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1009",
                            IsDeleted = false,
                            LicenseNumber = "L1009",
                            Mobile = "01000000009",
                            Name = "طارق يحيى",
                            PassportNumber = "P1009",
                            UnifiedNumber = "U1009"
                        },
                        new
                        {
                            Id = 10,
                            Birthday = new DateTime(1982, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1010",
                            IsDeleted = false,
                            LicenseNumber = "L1010",
                            Mobile = "01000000010",
                            Name = "حسن حمدي",
                            PassportNumber = "P1010",
                            UnifiedNumber = "U1010"
                        },
                        new
                        {
                            Id = 11,
                            Birthday = new DateTime(1993, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1011",
                            IsDeleted = false,
                            LicenseNumber = "L1011",
                            Mobile = "01000000011",
                            Name = "خالد زكي",
                            PassportNumber = "P1011",
                            UnifiedNumber = "U1011"
                        },
                        new
                        {
                            Id = 12,
                            Birthday = new DateTime(1978, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1012",
                            IsDeleted = false,
                            LicenseNumber = "L1012",
                            Mobile = "01000000012",
                            Name = "ماجد الكدواني",
                            PassportNumber = "P1012",
                            UnifiedNumber = "U1012"
                        },
                        new
                        {
                            Id = 13,
                            Birthday = new DateTime(1989, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1013",
                            IsDeleted = false,
                            LicenseNumber = "L1013",
                            Mobile = "01000000013",
                            Name = "أمير كرارة",
                            PassportNumber = "P1013",
                            UnifiedNumber = "U1013"
                        },
                        new
                        {
                            Id = 14,
                            Birthday = new DateTime(1996, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1014",
                            IsDeleted = false,
                            LicenseNumber = "L1014",
                            Mobile = "01000000014",
                            Name = "صالح جمعة",
                            PassportNumber = "P1014",
                            UnifiedNumber = "U1014"
                        },
                        new
                        {
                            Id = 15,
                            Birthday = new DateTime(1997, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1015",
                            IsDeleted = false,
                            LicenseNumber = "L1015",
                            Mobile = "01000000015",
                            Name = "عبد الله جمعة",
                            PassportNumber = "P1015",
                            UnifiedNumber = "U1015"
                        },
                        new
                        {
                            Id = 16,
                            Birthday = new DateTime(1991, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1016",
                            IsDeleted = false,
                            LicenseNumber = "L1016",
                            Mobile = "01000000016",
                            Name = "باسم مرسي",
                            PassportNumber = "P1016",
                            UnifiedNumber = "U1016"
                        },
                        new
                        {
                            Id = 17,
                            Birthday = new DateTime(1979, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1017",
                            IsDeleted = false,
                            LicenseNumber = "L1017",
                            Mobile = "01000000017",
                            Name = "حازم إمام",
                            PassportNumber = "P1017",
                            UnifiedNumber = "U1017"
                        },
                        new
                        {
                            Id = 18,
                            Birthday = new DateTime(1973, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1018",
                            IsDeleted = false,
                            LicenseNumber = "L1018",
                            Mobile = "01000000018",
                            Name = "عصام الحضري",
                            PassportNumber = "P1018",
                            UnifiedNumber = "U1018"
                        },
                        new
                        {
                            Id = 19,
                            Birthday = new DateTime(1976, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1019",
                            IsDeleted = false,
                            LicenseNumber = "L1019",
                            Mobile = "01000000019",
                            Name = "وائل جمعة",
                            PassportNumber = "P1019",
                            UnifiedNumber = "U1019"
                        },
                        new
                        {
                            Id = 20,
                            Birthday = new DateTime(1978, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1020",
                            IsDeleted = false,
                            LicenseNumber = "L1020",
                            Mobile = "01000000020",
                            Name = "محمد أبو تريكة",
                            PassportNumber = "P1020",
                            UnifiedNumber = "U1020"
                        },
                        new
                        {
                            Id = 21,
                            Birthday = new DateTime(1975, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1021",
                            IsDeleted = false,
                            LicenseNumber = "L1021",
                            Mobile = "01000000021",
                            Name = "أحمد حسن",
                            PassportNumber = "P1021",
                            UnifiedNumber = "U1021"
                        },
                        new
                        {
                            Id = 22,
                            Birthday = new DateTime(1992, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1022",
                            IsDeleted = false,
                            LicenseNumber = "L1022",
                            Mobile = "01000000022",
                            Name = "محمد صلاح",
                            PassportNumber = "P1022",
                            UnifiedNumber = "U1022"
                        },
                        new
                        {
                            Id = 23,
                            Birthday = new DateTime(1994, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1023",
                            IsDeleted = false,
                            LicenseNumber = "L1023",
                            Mobile = "01000000023",
                            Name = "محمود تريزيجيه",
                            PassportNumber = "P1023",
                            UnifiedNumber = "U1023"
                        },
                        new
                        {
                            Id = 24,
                            Birthday = new DateTime(1999, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1024",
                            IsDeleted = false,
                            LicenseNumber = "L1024",
                            Mobile = "01000000024",
                            Name = "عمر مرموش",
                            PassportNumber = "P1024",
                            UnifiedNumber = "U1024"
                        },
                        new
                        {
                            Id = 25,
                            Birthday = new DateTime(1997, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdNumber = "I1025",
                            IsDeleted = false,
                            LicenseNumber = "L1025",
                            Mobile = "01000000025",
                            Name = "مصطفى محمد",
                            PassportNumber = "P1025",
                            UnifiedNumber = "U1025"
                        });
                });

            modelBuilder.Entity("ZAD.Domain.Entities.VehicleRental.Vehicles.RentalVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRented")
                        .HasColumnType("bit");

                    b.Property<int>("KilometerCounter")
                        .HasColumnType("int");

                    b.Property<decimal>("MinimumRentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ModelYear")
                        .HasColumnType("int");

                    b.Property<string>("PlateNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CompanyId");

                    b.ToTable("RentalVehicles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "KIA",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileNo = "F-001",
                            IsDeleted = false,
                            IsRented = true,
                            KilometerCounter = 10000,
                            MinimumRentPrice = 10.00m,
                            ModelYear = 2026,
                            PlateNo = "77777"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "KIA",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileNo = "F-002",
                            IsDeleted = false,
                            IsRented = true,
                            KilometerCounter = 12000,
                            MinimumRentPrice = 12.00m,
                            ModelYear = 2026,
                            PlateNo = "3030"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "KIA",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileNo = "F-003",
                            IsDeleted = false,
                            IsRented = true,
                            KilometerCounter = 15000,
                            MinimumRentPrice = 11.00m,
                            ModelYear = 2026,
                            PlateNo = "EXT 1111"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Nissan Patrol",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileNo = "F-004",
                            IsDeleted = false,
                            IsRented = true,
                            KilometerCounter = 20000,
                            MinimumRentPrice = 30.00m,
                            ModelYear = 2026,
                            PlateNo = "ACB-4578"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Kia Sonet",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileNo = "F-005",
                            IsDeleted = false,
                            IsRented = true,
                            KilometerCounter = 8000,
                            MinimumRentPrice = 15.00m,
                            ModelYear = 2026,
                            PlateNo = "ABC 1245"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Kia Sonet",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileNo = "DEF 1478",
                            IsDeleted = false,
                            IsRented = false,
                            KilometerCounter = 40000,
                            MinimumRentPrice = 8.00m,
                            ModelYear = 2011,
                            PlateNo = "DEF 1478"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Toyota Corolla",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileNo = "F-007",
                            IsDeleted = false,
                            IsRented = false,
                            KilometerCounter = 5000,
                            MinimumRentPrice = 20.00m,
                            ModelYear = 2026,
                            PlateNo = "XYZ 999"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Toyota Camry",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileNo = "F-008",
                            IsDeleted = false,
                            IsRented = false,
                            KilometerCounter = 6000,
                            MinimumRentPrice = 25.00m,
                            ModelYear = 2026,
                            PlateNo = "LMN 456"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Honda Civic",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileNo = "F-009",
                            IsDeleted = false,
                            IsRented = false,
                            KilometerCounter = 7000,
                            MinimumRentPrice = 18.00m,
                            ModelYear = 2026,
                            PlateNo = "PQR 789"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Hyundai Elantra",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileNo = "F-010",
                            IsDeleted = false,
                            IsRented = false,
                            KilometerCounter = 9000,
                            MinimumRentPrice = 17.00m,
                            ModelYear = 2026,
                            PlateNo = "STU 123"
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Chevrolet Tahoe",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileNo = "F-011",
                            IsDeleted = false,
                            IsRented = false,
                            KilometerCounter = 25000,
                            MinimumRentPrice = 40.00m,
                            ModelYear = 2026,
                            PlateNo = "VWX 456"
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Ford Explorer",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileNo = "F-012",
                            IsDeleted = false,
                            IsRented = false,
                            KilometerCounter = 22000,
                            MinimumRentPrice = 35.00m,
                            ModelYear = 2026,
                            PlateNo = "YZA 789"
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Mazda CX-5",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileNo = "F-013",
                            IsDeleted = false,
                            IsRented = false,
                            KilometerCounter = 14000,
                            MinimumRentPrice = 22.00m,
                            ModelYear = 2026,
                            PlateNo = "BCD 012"
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Nissan Altima",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileNo = "F-014",
                            IsDeleted = false,
                            IsRented = false,
                            KilometerCounter = 11000,
                            MinimumRentPrice = 19.00m,
                            ModelYear = 2026,
                            PlateNo = "EFG 345"
                        },
                        new
                        {
                            Id = 15,
                            Brand = "BMW 3 Series",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileNo = "F-015",
                            IsDeleted = false,
                            IsRented = false,
                            KilometerCounter = 18000,
                            MinimumRentPrice = 45.00m,
                            ModelYear = 2026,
                            PlateNo = "HIJ 678"
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Mercedes C-Class",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileNo = "F-016",
                            IsDeleted = false,
                            IsRented = false,
                            KilometerCounter = 16000,
                            MinimumRentPrice = 48.00m,
                            ModelYear = 2026,
                            PlateNo = "KLM 901"
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Audi A4",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileNo = "F-017",
                            IsDeleted = false,
                            IsRented = false,
                            KilometerCounter = 17000,
                            MinimumRentPrice = 42.00m,
                            ModelYear = 2026,
                            PlateNo = "NOP 234"
                        },
                        new
                        {
                            Id = 18,
                            Brand = "Lexus ES",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileNo = "F-018",
                            IsDeleted = false,
                            IsRented = false,
                            KilometerCounter = 13000,
                            MinimumRentPrice = 38.00m,
                            ModelYear = 2026,
                            PlateNo = "QRS 567"
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Jeep Grand Cherokee",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileNo = "F-019",
                            IsDeleted = false,
                            IsRented = false,
                            KilometerCounter = 21000,
                            MinimumRentPrice = 36.00m,
                            ModelYear = 2026,
                            PlateNo = "TUV 890"
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Volkswagen Tiguan",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileNo = "F-020",
                            IsDeleted = false,
                            IsRented = false,
                            KilometerCounter = 19000,
                            MinimumRentPrice = 24.00m,
                            ModelYear = 2026,
                            PlateNo = "WXY 123"
                        },
                        new
                        {
                            Id = 21,
                            Brand = "Subaru Outback",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileNo = "F-021",
                            IsDeleted = false,
                            IsRented = false,
                            KilometerCounter = 24000,
                            MinimumRentPrice = 28.00m,
                            ModelYear = 2026,
                            PlateNo = "ZAB 456"
                        });
                });

            modelBuilder.Entity("ZAD.Domain.Entities.Branches.Branch", b =>
                {
                    b.HasOne("ZAD.Domain.Entities.Companies.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("ZAD.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<int>("BranchId")
                                .HasColumnType("int");

                            b1.Property<string>("AddressAr")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("AddressAr");

                            b1.Property<string>("AddressEn")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("AddressEn");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("City");

                            b1.Property<string>("Country")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Country");

                            b1.HasKey("BranchId");

                            b1.ToTable("Branches");

                            b1.WithOwner()
                                .HasForeignKey("BranchId");
                        });

                    b.OwnsMany("ZAD.Domain.Entities.Common.Contact", "Contacts", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("BranchId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)");

                            b1.HasKey("Id");

                            b1.HasIndex("BranchId");

                            b1.ToTable("BranchContacts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BranchId");
                        });

                    b.OwnsMany("ZAD.Domain.Entities.Common.Document", "Documents", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("BranchId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("DocumentNumber")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<DateTime?>("ExpiryDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("FilePath")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("datetime2");

                            b1.HasKey("Id");

                            b1.HasIndex("BranchId");

                            b1.ToTable("BranchDocuments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BranchId");
                        });

                    b.Navigation("Address");

                    b.Navigation("Company");

                    b.Navigation("Contacts");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("ZAD.Domain.Entities.Companies.Company", b =>
                {
                    b.OwnsOne("ZAD.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<int>("CompanyId")
                                .HasColumnType("int");

                            b1.Property<string>("AddressAr")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("AddressAr");

                            b1.Property<string>("AddressEn")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("AddressEn");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("City");

                            b1.Property<string>("Country")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Country");

                            b1.HasKey("CompanyId");

                            b1.ToTable("Companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.OwnsMany("ZAD.Domain.Entities.Common.Contact", "Contacts", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("CompanyId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)");

                            b1.HasKey("Id");

                            b1.HasIndex("CompanyId");

                            b1.ToTable("CompanyContacts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.OwnsMany("ZAD.Domain.Entities.Common.Document", "Documents", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("CompanyId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("DocumentNumber")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<DateTime?>("ExpiryDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("FilePath")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("datetime2");

                            b1.HasKey("Id");

                            b1.HasIndex("CompanyId");

                            b1.ToTable("CompanyDocuments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.Navigation("Address");

                    b.Navigation("Contacts");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("ZAD.Domain.Entities.VehicleRental.Contracts.Contract", b =>
                {
                    b.HasOne("ZAD.Domain.Entities.Branches.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ZAD.Domain.Entities.Companies.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ZAD.Domain.Entities.VehicleRental.Drivers.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ZAD.Domain.Entities.VehicleRental.Vehicles.RentalVehicle", "RentalVehicle")
                        .WithMany()
                        .HasForeignKey("RentalVehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZAD.Domain.Entities.VehicleRental.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Company");

                    b.Navigation("Driver");

                    b.Navigation("RentalVehicle");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ZAD.Domain.Entities.VehicleRental.Vehicles.RentalVehicle", b =>
                {
                    b.HasOne("ZAD.Domain.Entities.Branches.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ZAD.Domain.Entities.Companies.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Branch");

                    b.Navigation("Company");
                });
#pragma warning restore 612, 618
        }
    }
}
